stages:
  - build

docker-build:
  stage: build

  image:
    name: docker:latest

  services:
   - name: docker:dind
     alias: dockerdaemon

  variables:
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:CI_COMMIT_REF_NAME"
